name: Run Tests

on:  
  push:
    branches: 
      - main 
  pull_request: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change la version si besoin

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 🧪 Lancer les tests
        run: python3 -m unittest test_code.py
